version: "3"

services:
  garage-backend:
    container_name: garage-backend
    image: ialmostdeveloper/xsolla-garage-backend
    ports:
      - 8081:8081
    restart: always
  garage-frontend:
    container_name: garage-frontend
    image: ialmostdeveloper/xsolla-garage-frontend
    ports:
      - 9000:9000
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
            - 3307:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=XsollaGarage
