# This is a basic workflow to help you get started with Actions

name: ansible

on:
  push:
    branches: [ ansible-workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Run ansible command
        run: |
            ansible --version
            ls -a /
            echo "$VM_SSH_KEY"
            echo "$VM_SSH_KEY" > key
            sudo chmod 600 key
            ls -a /home/runner
            ansible -i hosts.txt all -m shell -a "uptime"
        shell: bash
        env:
          VM_SSH_KEY: ${{secrets.VM_SSH_KEY}}
